# score=99
# if score>=90:
#     print("grade:A")
# elif score >=80:
#   print("grade:B")
# elif score>=70:
#   print("grade:c")
# elif score >=60:
#   print("grade:D")

# age=100
# if age>=18:
#     print("to vote")
# elif age>=100:
#     print("not to vote")
# else:
#     print("")

# age= int(input("enter your age"))
# if age>=18:
#     print("you are eligible to vote")
# elif age >0:
#     print("you are not eligable to vote")
# else:
#     print("invalid age")

# temperature =float(input("enter the temp"))
# if temperature >30:
#     print("its hot")
# elif temperature >20:
#     print("its cool")
# else:
#     print("its cold")
            
# for i in range(1,300)
#     print(i)

# for i in range(20)
#     print("hello")


# numbers =[2,7,4,9,1]

# for num in numbers:
#     if num>5:
#         print(num,"is greater than 5")
#     else:
#         print(num,"is not greater than 5")

for i in range(5)
    num=int(imput("enter any number"))
else:
    print(num,"is not greater than 5")



